--- #YAML:1.0
name: Env-PS1
version: 0.03
author:
  - Jaap Karssenberg <pardus@cpan.org>
abstract: prompt string formatter
license: perl
requires:
  AutoLoader: 0
  POSIX: 0
  Sys::Hostname: 0
build_requires:
  AutoSplit: 0
provides:
  Env::PS1:
    file: lib/Env/PS1.pm
    version: 0.03
generated_by: Module::Build version 0.24
